### ISSUE TITLE
feat: upload a blob from ios/android

### ISSUE THREAD

**Issue by mesqueeb** [capawesome-team/capacitor-cloudinary#8]
I understand the main use case of this plugin to be:
- upload directly from a `path` when on ios/android. This will prevent some memory issues related to webview.

However, in some cases an app might still have some minor cases where they already have a blob and want to pass that (eg. an image created/edited on a canvas in the DOM; another example would be to have a client draw a signature on a canvas via a touch screen and save that in cloudinary).

So it will be helpful if we can still pass a blob even on ios and android, even though I understand this is not the main use case.

The docs could say something like this:

-- | -- | --
-- | -- | --
blob | Blob | The file to upload. For usage on the web. Also available on Android and iOS, but _not recommended_. Use `path` on Android and iOS to prevent memory issues when working with large files.

**Comment by robingenz** [comment]
Unfortunately, a Blob cannot be transferred via the native bridge. That's why the official Filesystem plugin supports only the type string for data (see [here](https://capacitorjs.com/docs/apis/filesystem#writefileoptions)). There is an [capacitor-blob-writer](https://www.npmjs.com/package/capacitor-blob-writer) plugin, but it has potential security risks (see [here](https://github.com/diachedelic/capacitor-blob-writer#known-limitations-and-issues)). I recommend to convert Blobs to base64 and to use the official Capacitor filesystem plugin if a file cannot be created directly on the native file system.

For this reason i am closing this issue.

Please let me know if you have any other ideas for implementation. Then we can open the issue again.

**Comment by mesqueeb** [comment]
Hey @robingenz 

I believe it can be helpful to not use the Swift integration at all in case a blob is passed. Meaning,whatever platform is used, if a blob is passed, the blob is uploaded via the web integration. 

When passing a path, the file will be uploaded via swift/java. 

There's no need to pass the blob to the native layer. 

I do understand that it defeats the purpose of this plugin, but it's helpful because otherwise some apps will need to implement this plugin and implement their own uploading logic next to it just for when they need to save a blob from the WebView while using iOS/android.

**Comment by robingenz** [comment]
Okay, got it. I can't modify the behavior of the Capacitor bridge but I can add a separate utils class, which can be directly used from every platform.
